const KEY='jinye_daily_reports_v1';
const $=id=>document.getElementById(id);
function getReports(){return JSON.parse(localStorage.getItem(KEY)||'[]')}
function saveReports(data){localStorage.setItem(KEY,JSON.stringify(data))}
function money(n){return Number(n||0).toFixed(0)}
function renderHistory(){const data=getReports();const el=$('history');if(!data.length){el.innerHTML='<p class="muted">还没有日报。今天收店后填一份，就会从这里开始积累。</p>';return}el.innerHTML=data.slice().reverse().map((r,i)=>`<div class="history-item"><strong>${r.date} · ${money(r.revenue)}元</strong><div class="muted">${r.tables}桌 · ${r.people}人 · 牛肉${r.beefKg}kg · 抖音${r.douyinTables}桌 · 播放${r.views}</div></div>`).join('')}
function analyze(r){const data=getReports();const avg=data.length?data.reduce((s,x)=>s+Number(x.revenue),0)/data.length:Number(r.revenue);const perPerson=r.people?Number(r.revenue)/Number(r.people):0;const perTable=r.tables?Number(r.revenue)/Number(r.tables):0;let trend='';if(data.length>1){const prev=data.slice(0,-1);const prevAvg=prev.reduce((s,x)=>s+Number(x.revenue),0)/prev.length;trend=Number(r.revenue)>=prevAvg?`今天比之前平均营业额高${money(Number(r.revenue)-prevAvg)}元。`:`今天比之前平均营业额低${money(prevAvg-Number(r.revenue))}元，需要重点关注客流。`}else trend='这是第一条数据，先不要急着判断好坏，连续记录7天后趋势会更有价值。';let tips=[];if(Number(r.people)<10)tips.push('今天人数偏少，明天内容重点放在“为什么值得专程来吃”而不是单纯展示环境。');if(Number(r.views)>0&&Number(r.douyinTables)===0)tips.push('有播放但没有记录抖音到店，明天可以在视频/直播里明确告诉顾客团购和到店方式。');if(Number(r.douyinTables)>0)tips.push(`今天有${r.douyinTables}桌抖音客，说明抖音已经能带来真实到店，继续记录哪些内容带客。`);if(Number(r.beefKg)>0&&Number(r.people)>0)tips.push(`今天人均牛肉约${(Number(r.beefKg)*1000/Number(r.people)).toFixed(0)}克，可以继续观察这个指标，帮助判断牛肉成本和客单。`);if(r.weather==='雨')tips.push('今天下雨，客流数据要和晴天分开看，不要单凭一天判断经营出了问题。');tips.push('明天继续记录：营业额、人数、桌数、牛肉、抖音客。数据积累起来后，AI才能真正找到你店里的规律。');$('summary').innerHTML=`<div class="metric">营业额<b>${money(r.revenue)}元</b></div><div class="metric">人均<b>${money(perPerson)}元</b></div><div class="metric">桌均<b>${money(perTable)}元</b></div><div class="metric">牛肉<b>${r.beefKg}kg</b></div><div class="metric">抖音客<b>${r.douyinTables}桌</b></div><div class="metric">播放<b>${Number(r.views).toLocaleString()}</b></div>`;$('advice').innerHTML=`<strong>店长判断</strong><br>${trend}<br><br><strong>明日建议</strong><br>• ${tips.join('<br>• ')}`;$('analysis').hidden=false}
$('dailyForm').addEventListener('submit',e=>{e.preventDefault();const r={date:new Date().toLocaleDateString('zh-CN'),revenue:$('revenue').value,tables:$('tables').value,people:$('people').value,beefKg:$('beefKg').value,drinks:$('drinks').value,newTables:$('newTables').value,oldTables:$('oldTables').value,douyinTables:$('douyinTables').value,views:$('views').value,weather:$('weather').value,feedback:$('feedback').value,content:$('content').value};const data=getReports();data.push(r);saveReports(data);analyze(r);renderHistory();e.target.reset();});
$('clearData').addEventListener('click',()=>{if(confirm('确定清空本机保存的日报吗？')){localStorage.removeItem(KEY);renderHistory();$('analysis').hidden=true}});renderHistory();
